name: Tweeter

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node it
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          ref: ${{ github.head_ref }}
      - name: Install it
        run: npm install
      - name: Config it
        run: |
          echo TWITTER_APP_KEY=${{ secrets.TWITTER_APP_KEY }} > .env
          echo TWITTER_APP_SECRET=${{ secrets.TWITTER_APP_SECRET }} >> .env
          echo TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }} >> .env
          echo TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }} >> .env
      - name: Tweet it
        run: node dist/scripts/tweet_a_mile.js
      - name: Commit it
        run: |
          git config --global user.name 'Jason Sanford'
          git config --global user.email 'jasonsanford@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Tweeted"
          git push
